apiVersion: v1
kind: PersistentVolume
metadata:
  name: tenant-pv16
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
